name: Check committer(s) email(s)

on:
  workflow_call:
    inputs:
      required_domain:
        default: 'aurora.dev'
        required: false
        type: string

jobs:
  check_emails:
    name: Check committer(s) email(s)
    runs-on: self-hosted
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Check branch commits
        if: github.base_ref != null
        run: |
          git fetch
          git cherry remotes/origin/master remotes/origin/test
          git cherry ${{ github.base_ref }}
      - name: Check current commit
        if: github.base_ref == null
        run: |
          git rev-parse HEAD
