name: Check committer(s) email(s)

on:
  workflow_call:
    inputs:
      required_domain:
        default: 'aurora.dev'
        required: false
        type: string

jobs:
  check_emails:
    name: Check committer(s) email(s)
    runs-on: self-hosted
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Check email(s)
        run: |
          base_ref=${{ github.base_ref }}
          head_ref=${{ github.head_ref }}
          required_domain=${{ inputs.required_domain }}

          git fetch &>/dev/null
          if [[ $base_ref == "" ]] || [[ $head_ref == "" ]]; then
              commits="+ $(git rev-parse HEAD)"
          else
              commits=$(git cherry remotes/origin/$base_ref remotes/origin/$head_ref)
          fi

          echo $commits | grep "+" | while read line ; do
              commit_hash=$(echo $line | awk '{print $2}')
              email=$(git show -s --format='%ae' $commit_hash)
              domain=$(echo $email | awk -F\@ '{print $2}')
              if [[ $domain == $required_domain ]]; then
                  echo $commit_hash ":" $email "- OK"
              else
                  echo $commit_hash ":" $email "- is not under domain $required_domain !!!"
                  exit 1
              fi
          done
