name: Check committer(s) email(s)

on:
  workflow_call:
    inputs:
      required_domain:
        default: 'aurora.dev'
        required: false
        type: string

jobs:
  check_emails:
    name: Check committer(s) email(s)
    runs-on: self-hosted
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2
      - name: Check email(s)
        run: |
          base_ref=${{ github.base_ref }}
          [[ $base_ref == "" ]] && base_ref="HEAD^1" || base_ref=remotes/origin/$base_ref
          head_ref=${{ github.head_ref }}
          [[ $head_ref == "" ]] && head_ref="HEAD" || head_ref=remotes/origin/$head_ref
          required_domain=${{ inputs.required_domain }}

          git cherry $base_ref $head_ref | grep "+" | while read line ; do
              commit_hash=$(echo $line | awk '{print $2}')
              email=$(git show -s --format='%ae' $commit_hash)
              domain=$(echo $email | awk -F\@ '{print $2}')
              if [[ $domain == $required_domain ]]; then
                  echo $commit_hash ":" $email "- OK"
              else
                  echo $commit_hash ":" $email "- is not under domain $domain !!!"
                  exit 1
              fi
          done
