name: Smart Contract Security Analysis

on:
  workflow_call:
    inputs:
      force_all_checks:
        required: false
        type: string
        description: "Trigger all checks even if files are unchanged"

env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  scheduler:
    name: Backstage
    runs-on: [self-hosted, light]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        if: always()
        continue-on-error: true
        with:
          ssh-private-key: ${{ secrets.BACKSTAGE_ENTITIES_SSH_KEY }}
      - uses: aurora-is-near/github-helpers@main
        id: component_matrix
        env:
          ENTITIES_REPO: ${{ github.repository_visibility == 'private' && 'backstage-entities-private' || 'backstage-entities' }}
        with:
          helper: generate-component-matrix
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backstage_url: ${{ secrets.BACKSTAGE_URL }}
          backstage_entities_repo: aurora-is-near/${{env.ENTITIES_REPO}}
          force_all_checks: ${{ inputs.force_all_checks }}
    outputs:
      matrix: ${{ steps.component_matrix.outputs.output }}

  build:
    name: Static Analysis
    runs-on: [self-hosted, light]
    needs: scheduler
    strategy:
      matrix: ${{ fromJson(needs.scheduler.outputs.matrix) }}
      fail-fast: false
    steps:
      - run: echo "Run for ${{ matrix.component }} at ${{ matrix.path }}"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup repo variables (.env.example)
        run: test -f .env.example && cat .env.example >> "$GITHUB_ENV" || true
      - name: Setup component variables (.env.example)
        working-directory: ${{ matrix.path }}
        run: test -f .env.example && cat .env.example >> "$GITHUB_ENV" || true
      - name: Setup repo variables (Makefile)
        run: test -f Makefile && make env >> "$GITHUB_ENV" || true
      - name: Setup component variables (Makefile)
        working-directory: ${{ matrix.path }}
        run: test -f Makefile && make env >> "$GITHUB_ENV" || true
      - name: Run Slither
        uses: aurora-is-near/slither-action@main
        if: always() && matrix.runSlither
        id: slither
        with:
          target: ${{ matrix.nodeRoot }}
          node-version: 18
          slither-args: ${{ matrix.slitherArgs }}
      - uses: webfactory/ssh-agent@v0.7.0
        if: always()
        continue-on-error: true
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Run Clippy
        if: always() && matrix.runClippy
        id: clippy
        working-directory: ${{ matrix.path }}
        run: cargo clippy --no-deps --lib -- -D clippy::as_conversions
      - name: Run Clippy (all)
        if: always() && matrix.runClippy
        continue-on-error: true
        id: clippy-all
        working-directory: ${{ matrix.path }}
        run: cargo clippy --all-targets --no-deps --lib -- -D clippy::all || true
