name: Smart Contract Security Analysis

on:
  workflow_call:

jobs:
  scheduler:
    name: Backstage
    runs-on: [self-hosted, light]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: aurora-is-near/github-helpers@main
        id: component_matrix
        with:
          helper: generate-component-matrix
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backstage_url: ${{ secrets.BACKSTAGE_URL }}
    outputs:
      matrix: ${{ steps.component_matrix.outputs.output }}

  build:
    name: Static Analysis
    runs-on: [self-hosted, light]
    needs: scheduler
    strategy:
      matrix: ${{ fromJson(needs.scheduler.outputs.matrix) }}
      fail-fast: false
    steps:
      - run: echo "Run for ${{ matrix.component }} at ${{ matrix.path }}"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup repo variables (.env.example)
        run: test -f .env.example && cat .env.example >> "$GITHUB_ENV" || true
      - name: Setup component variables (.env.example)
        working-directory: ${{ matrix.path }}
        run: test -f .env.example && cat .env.example >> "$GITHUB_ENV" || true
      - name: Setup repo variables (Makefile)
        run: test -f Makefile && make env >> "$GITHUB_ENV" || true
      - name: Setup component variables (Makefile)
        working-directory: ${{ matrix.path }}
        run: test -f Makefile && make env >> "$GITHUB_ENV" || true
      - name: Run Slither
        uses: aurora-is-near/slither-action@main
        if: always() && matrix.runSlither
        id: slither
        with:
          target: ${{ matrix.nodeRoot }}
          slither-args: '--filter-paths "node_modules|testing" --exclude timestamp,solc-version,naming-convention,assembly-usage'
      - name: Run Clippy
        if: always() && matrix.runClippy
        id: clippy
        working-directory: ${{ matrix.path }}
        run: cargo clippy --no-deps --lib -- -D clippy::as_conversions
