name: Quality & Security Analysis
on:
  workflow_call:
    inputs:
      force_all_checks:
        required: false
        type: string
        description: "Trigger all checks even if files are unchanged"
      ignore_failures:
        required: false
        type: string
        description: "Don't block CI on failed security checks"
env:
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  scheduler:
    runs-on: ubuntu-latest
    name: Backstage
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: webfactory/ssh-agent@v0.9.0
        continue-on-error: true
        with:
          ssh-private-key: ${{ secrets.BACKSTAGE_ENTITIES_SSH_KEY }}

      - uses: aurora-is-near/github-helpers@main
        id: component_matrix
        env:
          ENTITIES_REPO: ${{ github.repository_visibility == 'private' && 'backstage-entities-private' || 'backstage-entities' }}
        with:
          helper: generate-component-matrix
          github_token: ${{ secrets.GITHUB_TOKEN }}
          backstage_url: ${{ secrets.BACKSTAGE_URL }}
          backstage_entities_repo: aurora-is-near/${{env.ENTITIES_REPO}}
          force_all_checks: ${{ inputs.force_all_checks }}
          ignore_failures: ${{ inputs.ignore_failures }}
    outputs:
      matrix: ${{ steps.component_matrix.outputs.output }}

  build:
    name: Static Analysis
    runs-on: ubuntu-latest
    needs: scheduler
    strategy:
      matrix: ${{ fromJson(needs.scheduler.outputs.matrix) }}
      fail-fast: false
    steps:
      - run: |
          echo Run for ${{ matrix.name }} at ${{ matrix.path }}
          echo '${{ toJson(matrix) }}'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup repo variables (.env.example)
        run: test -f .env.example && cat .env.example >> "$GITHUB_ENV" || true
      - name: Setup component variables (.env.example)
        working-directory: ${{ matrix.path }}
        run: test -f .env.example && cat .env.example >> "$GITHUB_ENV" || true

      - name: Setup repo variables (Makefile)
        run: test -f Makefile && make env >> "$GITHUB_ENV" || true
      - name: Setup component variables (Makefile)
        working-directory: ${{ matrix.path }}
        run: test -f Makefile && make env >> "$GITHUB_ENV" || true

      - name: Run Slither
        uses: crytic/slither-action@v0.4.0
        if: always() && matrix.runSlither
        continue-on-error: true
        id: slither
        with:
          target: ${{ matrix.nodeRoot == '' && '.' || matrix.nodeRoot }}
          node-version: 18
          slither-args: ${{ matrix.slitherArgs }}

      - uses: webfactory/ssh-agent@v0.9.0
        if: always()
        continue-on-error: true
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install Clippy
        if: always() && matrix.runClippy
        continue-on-error: ${{ matrix.allowTestsToFail }}
        id: clippy-install
        working-directory: ${{ matrix.path }}
        run: rustup component add clippy-preview

      - name: Run Clippy
        if: always() && matrix.runClippy
        continue-on-error: ${{ matrix.allowTestsToFail }}
        id: clippy
        working-directory: ${{ matrix.path }}
        run: cargo clippy --all-targets --no-deps --lib -- -D clippy::as_conversions

      - name: Run Clippy (all)
        if: always() && matrix.runClippy
        continue-on-error: true
        id: clippy-all
        working-directory: ${{ matrix.path }}
        run: cargo clippy --all-targets --no-deps --lib -- -D clippy::all -D clippy::pedantic || true

      - name: Setup Go
        continue-on-error: ${{ matrix.allowTestsToFail }}
        uses: WillAbides/setup-go-faster@v1.14.0
        if: always() && matrix.runGoStaticChecks
        id: setup-go
        with:
          go-version: ${{ matrix.goVersion }}

      - name: Run Go Vet
        if: always() && matrix.runGoStaticChecks
        continue-on-error: ${{ matrix.allowTestsToFail }}
        id: go-vet
        run: "go vet ./${{ matrix.path }}/..."

      - name: Run Go Staticcheck
        uses: dominikh/staticcheck-action@v1
        if: always() && matrix.runGoStaticChecks
        continue-on-error: ${{ matrix.allowTestsToFail }}
        id: go-staticcheck
        with:
          version: "2023.1.6"
          install-go: false
          cache-key: ${{ matrix.goVersion }}
          working-directory: ${{ matrix.path }}

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: 1.9.4
      - name: Run Biome
        continue-on-error: true
        run: biome lint .
